# Site settings
title: satPerf
email: netsys.surrey@gmail.com
url: https://github.com/socsys/slinky-test
description: "It is a Chrome Browser extension developed by University of Surrey as part of study to understand the performance of SpaceX's Starlink satellite network from users' persepctive."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: https://github.com/socsys/slinky-test

# Build settings
markdown: kramdown
permalink: pretty
